import { DEFAULT_DISPLAY_CONFIG } from "@skyos/skylight";
import type { SkyConfig } from "./types";

export function createDefaultSkyConfig(): SkyConfig {
  const d = DEFAULT_DISPLAY_CONFIG;
  return {
    centerLat: -33.79757042903397,
    centerLon: 151.1853986392743,
    altitudeM: 25,
    locationName: "Sydney",
    radiusKm: 50,
    refreshSecs: 1,
    locationProfiles: [],

    remoteControlEnabled: false,
    configSyncEnabled: false,
    remoteAccessToken: "",

    viewMode: "dome",
    aircraftFilter: "all",

    showCallsign: true,
    showAltitude: true,
    showSpeed: true,
    showHeading: false,
    showRoute: true,
    showAirline: true,
    showType: true,
    showRegistration: false,
    airportCodeFormat: "icao",
    showTrails: true,
    showRunways: true,
    showHorizon: true,
    useAltitudeColor: true,
    useDistanceScale: true,
    iconScale: 1,
    interpolateMotion: true,
    renderFpsMode: "display",
    renderFps: 60,

    ceilingBearingDeg: 0,
    ceilingBearingLocked: false,
    ceilingProjectionMode: "sky",
    ceilingMirrorX: true,
    ceilingMirrorY: false,
    ceilingLabelRotationDeg: 0,
    ceilingTheme: d.theme,
    ceilingBrightness: 1,
    ceilingGlyphSizePx: 22,
    ceilingLabelDensity: "all",
    ceilingNearestN: 5,
    ceilingHighlightEmergency: true,
    ceilingShowDestArc: true,
    ceilingShowRouteDetail: false,
    ceilingTrailSeconds: 45,
    ceilingStaleSec: 20,
    ceilingMaxExtrapolationSec: 5,
    ceilingShowStars: true,
    ceilingShowSun: true,
    ceilingShowMoon: true,
    ceilingShowPlanets: true,
    ceilingShowSatellites: true,
    ceilingSatelliteLabels: false,
    ceilingStarMagLimit: 2.6,
    ceilingStarLabelMagLimit: 0.3,
    ceilingSkyTimeOffsetMin: 0,

    rotationDeg: d.rotationDeg,
    mirrorX: d.mirrorX,
    mirrorY: d.mirrorY,
    labelRotationDeg: d.labelRotationDeg,
    projectionMode: d.projectionMode,
    minAltitudeFt: d.minAltitudeFt,
    maxAltitudeFt: d.maxAltitudeFt,
    hideOnGround: d.hideOnGround,
    interpolate: d.interpolate,
    maxExtrapolationSec: d.maxExtrapolationSec,
    staleSec: d.staleSec,
    smoothing: d.smoothing,
    maxFps: d.maxFps,
    theme: d.theme,
    palette: { ...d.palette },
    glyphSizePx: d.glyphSizePx,
    altitudeColor: d.altitudeColor,
    trailSeconds: d.trailSeconds,
    brightness: d.brightness,
    labelDensity: d.labelDensity,
    nearestN: d.nearestN,
    showFields: { ...d.showFields },
    speedUnit: d.speedUnit,
    rangeRings: d.rangeRings,
    compass: d.compass,
    highlightEmergency: d.highlightEmergency,
    showAirport: d.showAirport,
    showHud: d.showHud,
    showStars: d.showStars,
    showSun: d.showSun,
    showMoon: d.showMoon,
    showSatellites: d.showSatellites,
    satelliteLabels: d.satelliteLabels,
    showPlanets: d.showPlanets,
    starMagLimit: d.starMagLimit,
    starLabelMagLimit: d.starLabelMagLimit,
    skyTimeOffsetMin: d.skyTimeOffsetMin,
    showDestArc: d.showDestArc,
    showRouteDetail: d.showRouteDetail,
  };
}

export const DEFAULT_SKY_CONFIG = createDefaultSkyConfig();
